apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "userservice.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "userservice.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.containerPort | quote }}
  DB_URL: {{ .Values.config.dbUrl | default (printf "jdbc:mysql://%s-mysql:3306/userservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC" (include "userservice.fullname" .)) | quote }}
  ADMIN_EMAIL: {{ .Values.config.adminEmail | quote }}
  ADMIN_FIRST_NAME: {{ .Values.config.adminFirstName | quote }}
  ADMIN_LAST_NAME: {{ .Values.config.adminLastName | quote }}
  CLIENT_ID: {{ .Values.config.clientId | quote }}
  REDIRECT_URI: {{ .Values.config.redirectUri | quote }}
  ISSUER_URI: {{ .Values.config.issuerUri | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
