apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "userservice.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "userservice.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ include "userservice.fullname" . }}-secret
    creationPolicy: Owner
  data:
    # DB credentials
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.externalSecrets.dbSecretName }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.dbSecretName }}
        property: password
    # App secrets
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.appSecretName }}
        property: ADMIN_PASSWORD
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.appSecretName }}
        property: CLIENT_SECRET
