apiVersion: v1
kind: Secret
metadata:
  name: {{ include "userservice.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "userservice.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.secrets.dbUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | b64enc | quote }}
  CLIENT_SECRET: {{ .Values.secrets.clientSecret | b64enc | quote }}
