apiVersion: v1
kind: Service
metadata:
  name: {{ include "userservice.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "userservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "userservice.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
    - name: issuer
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
