ALTER TABLE jwt
    ADD user_id BINARY(16) NULL;

ALTER TABLE jwt
    MODIFY user_id BINARY(16) NOT NULL;

ALTER TABLE jwt
    ADD CONSTRAINT FK_JWT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);